[package]
name = "belajar-dasar-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
clap = { version = "4.5.42", features = ["derive"] }
axum = "0.8.4"
